In [2]:
import numpy as np 

ARRAYS 

In [3]:
a = np.array([1,2,3,4,5,6])

In [4]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [5]:
a[0], b[0]

(1, array([1, 2, 3, 4]))

In [6]:
b[0,0]

1

In [7]:
b [1, :]

array([5, 6, 7, 8])

COMO CRIAR ARRAYS BÁSICOS 

In [8]:
#Criando arrays de zeros 
np.zeros(2)

array([0., 0.])

In [9]:
#Criando arrays de 1 
np.ones(2)

array([1., 1.])

In [10]:
#Cria um array aleatório que varia com a memória
np.empty(3)

array([4.63745064e-310, 0.00000000e+000, 6.91422745e-310])

In [11]:
#Criando um array com um alcance de elementes 
np.arange(4)

array([0, 1, 2, 3])

In [12]:
#Criando um array com alcance e passos 
#np.arange(primeiro número, alcance , passo) 
np.arange(2,9,2)

array([2, 4, 6, 8])

In [13]:
#Cria um array com valores espaçados por um intervalo linear 
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
#Especificando o tipo de dado 
np.ones(2, dtype= np.int8)

array([1, 1], dtype=int8)

ADIONANDO, REMOVENDO E ORDENANDO ELEMENTOS  

In [15]:
#Ordenando 
a = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [16]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
a = np.array([[1,4],[3,1]])
np.sort(a) 

array([[1, 4],
       [1, 3]])

In [18]:
np.sort(a, axis= 0)

array([[1, 1],
       [3, 4]])

In [19]:
np.sort(a, axis= None)

array([1, 1, 3, 4])

In [20]:
tipodedado = [('name', 'S10'), ('height', float), ('age', int)] 
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),('Galahad', 1.7, 38)] 
a = np.array(values, dtype= tipodedado)
np.sort(a, order='height')

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [21]:
np.sort(a, order=['age', 'height']) 

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [22]:
#Concatenando arrays 
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [23]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]]) 
np.concatenate((x,y), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
np.concatenate((x,y.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [26]:
np.concatenate((x,y), axis = None)

array([1, 2, 3, 4, 5, 6])

In [27]:
#Removendo um elemento  
a = np.arange(0,4)
a = np.delete(a, 2) 
a

array([0, 1, 3])

MEDINDO FORMA E TAMANHO DE UM ARRAY

In [28]:
array_example = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],[[0, 1, 2, 3],[4, 5, 6, 7]],[[0 ,1 ,2, 3],[4, 5, 6, 7]]])

In [29]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [30]:
array_example.ndim

3

In [31]:
array_example.size

24

In [32]:
array_example.shape

(3, 2, 4)

REMOLDANDO O UM ARRAY 

In [33]:
a = np.arange(6) 
a

array([0, 1, 2, 3, 4, 5])

In [34]:
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

CONVERTENDO UM 1D ARRAY PARA UM 2D ARRAY

In [35]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape 

(6,)

In [36]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [40]:
row_vector = a[np.newaxis, :]
row_vector.shape


(1, 6)

In [41]:
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [43]:
col_vector = a[:, np.newaxis]
col_vector.shape 


(6, 1)

In [42]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [39]:
b = np.expand_dims(a, axis=1)
b.shape 


(6, 1)

In [44]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [45]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [47]:
c

array([[1, 2, 3, 4, 5, 6]])

In [48]:
d = np.expand_dims(a, axis=(0, 1))
d.shape

(1, 1, 6)

In [49]:
d


array([[[1, 2, 3, 4, 5, 6]]])

In [51]:
e = np.expand_dims(a, axis=(2, 0))
e.shape

(1, 6, 1)

In [52]:
e

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6]]])

IDEXAÇÃO E FATIAMENTO 

In [53]:
data = np.array([1,2,3]) 
data[1]

2

In [54]:
data[0:2]

array([1, 2])

In [55]:
data[1:]

array([2, 3])

In [56]:
data[-2:]

array([2, 3])

In [57]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [58]:
a[a<5]

array([1, 2, 3, 4])

In [63]:
five_up = (a>=5)
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [64]:
divisible_by_2 = a[a%2==0] 
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

In [65]:
c = a[(a>2)&(a<11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
five_up = (a>5) | (a==5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [67]:
b = np.nonzero(a<5) 
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [71]:
list_of_coordinates= list(zip(b[0], b[1]))

In [74]:
for coord in list_of_coordinates: 
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [72]:
print(a[b])

[1 2 3 4]


In [75]:
not_there = np.nonzero(a == 42) 
not_there

(array([], dtype=int64), array([], dtype=int64))