In [1]:
import numpy as np 

ARRAYS 

In [2]:
a = np.array([1,2,3,4,5,6])

In [3]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [4]:
a[0], b[0]

(1, array([1, 2, 3, 4]))

In [5]:
b[0,0]

1

In [6]:
b [1, :]

array([5, 6, 7, 8])

COMO CRIAR ARRAYS BÁSICOS 

In [7]:
#Criando arrays de zeros 
np.zeros(2)

array([0., 0.])

In [8]:
#Criando arrays de 1 
np.ones(2)

array([1., 1.])

In [9]:
#Cria um array aleatório que varia com a memória
np.empty(3)

array([0.0e+000, 0.0e+000, 1.6e-322])

In [10]:
#Criando um array com um alcance de elementes 
np.arange(4)

array([0, 1, 2, 3])

In [11]:
#Criando um array com alcance e passos 
#np.arange(primeiro número, alcance , passo) 
np.arange(2,9,2)

array([2, 4, 6, 8])

In [12]:
#Cria um array com valores espaçados por um intervalo linear 
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
#Especificando o tipo de dado 
np.ones(2, dtype= np.int8)

array([1, 1], dtype=int8)

ADIONANDO, REMOVENDO E ORDENANDO ELEMENTOS  

In [14]:
#Ordenando 
a = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [15]:
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
a = np.array([[1,4],[3,1]])
np.sort(a) 

array([[1, 4],
       [1, 3]])

In [17]:
np.sort(a, axis= 0)

array([[1, 1],
       [3, 4]])

In [18]:
np.sort(a, axis= None)

array([1, 1, 3, 4])

In [19]:
tipodedado = [('name', 'S10'), ('height', float), ('age', int)] 
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),('Galahad', 1.7, 38)] 
a = np.array(values, dtype= tipodedado)
np.sort(a, order='height')

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [20]:
np.sort(a, order=['age', 'height']) 

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])

In [21]:
#Concatenando arrays 
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [22]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]]) 
np.concatenate((x,y), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
np.concatenate((x,y.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [25]:
np.concatenate((x,y), axis = None)

array([1, 2, 3, 4, 5, 6])

In [26]:
#Removendo um elemento  
a = np.arange(0,4)
a = np.delete(a, 2) 
a

array([0, 1, 3])

MEDINDO FORMA E TAMANHO DE UM ARRAY

In [27]:
array_example = np.array([[[0, 1, 2, 3],[4, 5, 6, 7]],[[0, 1, 2, 3],[4, 5, 6, 7]],[[0 ,1 ,2, 3],[4, 5, 6, 7]]])

In [28]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [29]:
array_example.ndim

3

In [30]:
array_example.size

24

In [31]:
array_example.shape

(3, 2, 4)

REMOLDANDO O UM ARRAY 

In [32]:
a = np.arange(6) 
a

array([0, 1, 2, 3, 4, 5])

In [33]:
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

CONVERTENDO UM 1D ARRAY PARA UM 2D ARRAY

In [34]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape 

(6,)

In [35]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [36]:
row_vector = a[np.newaxis, :]
row_vector.shape


(1, 6)

In [37]:
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [38]:
col_vector = a[:, np.newaxis]
col_vector.shape 


(6, 1)

In [39]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [40]:
b = np.expand_dims(a, axis=1)
b.shape 


(6, 1)

In [41]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [42]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [43]:
c

array([[1, 2, 3, 4, 5, 6]])

In [44]:
d = np.expand_dims(a, axis=(0, 1))
d.shape

(1, 1, 6)

In [45]:
d


array([[[1, 2, 3, 4, 5, 6]]])

In [46]:
e = np.expand_dims(a, axis=(2, 0))
e.shape

(1, 6, 1)

In [47]:
e

array([[[1],
        [2],
        [3],
        [4],
        [5],
        [6]]])

IDEXAÇÃO E FATIAMENTO 

In [48]:
data = np.array([1,2,3]) 
data[1]

2

In [49]:
data[0:2]

array([1, 2])

In [50]:
data[1:]

array([2, 3])

In [51]:
data[-2:]

array([2, 3])

In [52]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [53]:
a[a<5]

array([1, 2, 3, 4])

In [54]:
five_up = (a>=5)
a[five_up]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [55]:
divisible_by_2 = a[a%2==0] 
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

In [56]:
c = a[(a>2)&(a<11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
five_up = (a>5) | (a==5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [58]:
b = np.nonzero(a<5) 
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [59]:
list_of_coordinates= list(zip(b[0], b[1]))

In [60]:
for coord in list_of_coordinates: 
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [61]:
print(a[b])

[1 2 3 4]


In [62]:
not_there = np.nonzero(a == 42) 
not_there

(array([], dtype=int64), array([], dtype=int64))

CRIANDO UM ARRAT DE UM DADO EXISTENTE

In [63]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
arr1 = a[3:8] 
arr1

array([4, 5, 6, 7, 8])

In [65]:
a1 = np.array([[1, 1],[2, 2]])

a2 = np.array([[3, 3],[4, 4]])

In [66]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [67]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [68]:
#Separando uma array
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
#Separando em 3 partes iguais 
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [70]:
#Caso você queira separar seu array depois da terceira e quarta coluna
np.hsplit(x, (3, 4))


[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [71]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [72]:
b1 = a[0,:] 
b1

array([1, 2, 3, 4])

In [73]:
b1[0] = 99
b1

array([99,  2,  3,  4])

In [74]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [75]:
#Usando o método da cópia

b2 = a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
b3 = b1.copy() 
b3[0]=1 
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

OPERAÇÕES BÁSICAS COM ARRAYS

In [77]:
data = np.array([1,2]) 
ones = np.ones(2, dtype=int) 
data + ones

array([2, 3])

In [78]:
data - ones

array([0, 1])

In [79]:
data*data 

array([1, 4])

In [80]:
data/data

array([1., 1.])

In [81]:
a = np.array([1,2,3,4]) 
a.sum()

10

In [82]:
b = np.array([[1,1],[2,2]])

In [83]:
b.sum(axis=0)

array([3, 3])

In [84]:
b.sum(axis=1)

array([2, 4])

In [85]:
data = np.array([1.0,2.0]) 
data * 1.6

array([1.6, 3.2])

In [86]:
data.max()

2.0

In [87]:
data.min()


1.0

In [88]:
data.sum()

3.0

In [89]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [90]:
a.sum()

4.8595784

In [91]:
a.min()

0.05093587

In [92]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [93]:
a.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

CRIANDO MATRIZES 

In [94]:
#2D arrays são matrizes 
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [95]:
data[0,1]

2

In [96]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [97]:
data[0:2, 0]

array([1, 3])

In [98]:
data.max()

6

In [99]:
data.min()

1

In [100]:
data.sum()

21

In [101]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [102]:
data.max(axis=0)

array([5, 6])

In [103]:
data.max(axis=1)

array([2, 5, 6])

In [104]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [105]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [106]:
#O jeito simples de se gerar números aleatórios
rng = np.random.default_rng(0)
rng.random(3)

array([0.63696169, 0.26978671, 0.04097352])

In [107]:
rng.random((3, 2))

array([[0.01652764, 0.81327024],
       [0.91275558, 0.60663578],
       [0.72949656, 0.54362499]])

In [108]:
np.ones(3)

array([1., 1., 1.])

In [109]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [110]:
np.zeros(3)

array([0., 0., 0.])

In [111]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

GERANDO NÚMEROS ALEATÓRIOS 

In [112]:
#Gerando números de 0 a 4 em uma matriz 2 x 4 
rng.integers(5, size=(2, 4))

array([[2, 4, 1, 4],
       [3, 0, 1, 4]])

PEGANDO VALORES ÚNICOS E CONTANDO 

In [113]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [114]:
#Pegando os valores únicos 
uniques_values = np.unique(a)
uniques_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [115]:
#Pegando o índice dos valores únicos 
uniques_values,indices_list = np.unique(a, return_index=True)

In [116]:
indices_list

array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14])

In [117]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
occurrence_count

array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1])

In [118]:
#Para matrizes
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [119]:
unique_values = np.unique(a_2d)
uniques_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [120]:
#Pegando linhas únicas
unique_rows = np.unique(a_2d, axis=0)
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [121]:
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)

In [122]:
unique_rows

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [123]:
indices

array([0, 1, 2])

In [124]:
occurrence_count

array([2, 1, 1])

TRANSPONDO E REMOLDANDO MATRIZES 

In [125]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [127]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [128]:
#Transpondo 
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [129]:
#OU 
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

COMO REVERTER UM ARRAY 

In [130]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])


In [131]:
#Revertendo 1D arrays
reversed_arr = np.flip(arr) 
reversed_arr

array([8, 7, 6, 5, 4, 3, 2, 1])

In [132]:
#Revertendo 2D arrays 
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [134]:
reversed_arr = np.flip(arr_2d)
reversed_arr

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [136]:
#Revertendo as linhas
reversed_arr_rows = np.flip(arr_2d, axis=0)
reversed_arr_rows

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [137]:
#Revertendo as colunas
reversed_arr_colums = np.flip(arr_2d, axis=1) 
reversed_arr_colums

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [138]:
#Revertendo apenas uma linha 
arr_2d[1] = np.flip(arr_2d[1]) 
arr_2d

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [139]:
#Revertendo uma coluna 
arr_2d[:,1] = np.flip(arr_2d[:,1]) 
arr_2d

array([[ 1, 10,  3,  4],
       [ 8,  7,  6,  5],
       [ 9,  2, 11, 12]])

REMOLDANDO E AFINANDO NDARRAYS 

In [140]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [141]:
#"Afinando o array" , não afeta arrays parentes 
a1 = x.flatten() 
a1[0]= 99 
x, a1

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [142]:
#Esse método afeta arrays parentes 
a2 = x.ravel() 
a2[0] = 98 
x, a2

(array([[98,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([98,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

SALVANDO E CARREGANDO ONJETOS NP 

In [143]:
a = np.array([1, 2, 3, 4, 5, 6]) 
np.save("filename", a)


In [144]:
b = np.load("filename.npy") 
b

array([1, 2, 3, 4, 5, 6])

In [145]:
#Salvando como um csv 
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [146]:
np.savetxt("new_file.csv", csv_arr) 

In [147]:
np.loadtxt("new_file.csv")

array([1., 2., 3., 4., 5., 6., 7., 8.])